development:
  adapter: postgresql
  encoding: unicode
  database: rportal_development
  pool: 5
  username: james
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: rportal_test
  pool: 5
  username: james
  password:

cucumber:
  <<: *test
